[project]
name = "soleos"
dynamic = ["version"]
description = "Customization for Soleos"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "geopy~=2.4.1"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"


[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<17.0.0"